### ISSUE TITLE
Not option to build apk.

### ISSUE THREAD

**Issue by axeforeverjumo** [maheshkurmi/-Android-Super-Mario#2]
I want to change the fire by bottles, a joke for my girl, but i am new.... and i open in android studio, and ii cant buiild it..... help me please.  dont know what to do.

**Comment by maheshkurmi** [comment]
The android project at github is an eclipse project, try importing it as eclipse project in netbeans ide.

**Comment by axeforeverjumo** [comment]
Neatbeans doesn't recognize the project, I installed Eclipse Java and a plugin but I'm not sure what I would have to do to work with the project and create an apk for a mobile phone. Forgive my ignorance.

**Comment by maheshkurmi** [comment]
In Eclipse:
1. install adt plugin
2. import  this project as android project
3. in project properties>>build path check if android  libraries are loaded
4. run app in emulator, 
5. now you can find apk in bin folder 

BTW why dont you create new android  project in netbeans and paste code in its src directory and assets in its assets directory.

**Comment by axeforeverjumo** [comment]
I did it and solved it, really thanks!
